# SPDX-FileCopyrightText: 2022 TomTom <http://tomtom.com>
# SPDX-License-Identifier: Apache-2.0

---

name: Run Test

on:
  pull_request:

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test
